baseURL = "https://GitHub-Adminstrator.github.io/Social_science_project_final.git"
title = "Pokemon API Project"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Jonas Hoffmann (s204071)", "Mathias B. Sørensen (s194366)", "Joachim S. Andersson (s204096)"]
    notebook = "explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/GitHub-Adminstrator/Social_science_project_final.git"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"
    [[params.nav]]
        label = "Discussion"
        link = "/discussion"

